import { app, BrowserWindow, ipcMain } from "electron";
import { Client } from "hag-network-client";
import { ip, port } from "hag-network-client/dist/env";
import { ResponseType } from "hag-network-client/dist/protolinking/classKeys";
import Long from "long";

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let client: Client;

ipcMain.on("startClient", (event, data) => {
  if (!client) {
    startClient(event.sender, data.userName, data.password);
  }
});

ipcMain.handle("GetMissionDetailsRequest", async (event, data) => {
  const result = await new Promise(res => {client.sendPacket("GetMissionDetailsRequest", data, res)});
  return result;
})

function startClient(webContents: Electron.WebContents, userName: string, password: string) {
  client = new Client(ip, port, webContents.userAgent, userName, password);
  const startTime = Date.now();
  client.once("loggedin", async () => {
    webContents.send("loggedin");
    client.sendPacket("subscribewarmapview");
  }).on("loginFailed", () => {
    webContents.mainFrame.executeJavaScript("alert('Login failed!');");
    // TODO Add try again logic
  }).on("join_war_response", async (data: { msg: ResponseType, redirectSrv?: string; }) => {
    if (data.msg === ResponseType.ok) {
      if (data.redirectSrv) {
        console.log(`redirectSrv detected: ${data.redirectSrv}`);
      }
      client.sendPacket("unsubscribewarmapview");
      setTimeout(() => {
        client.sendPacket("subscribewarmapview");
      }, 500);
    } else {
      console.error(`ERROR: ${data}`);
    }
  }).on("message", async (typetext, data) => {
    if (typetext == "KeyValueChangeSet") {
      if (data?.set) {
        let battlefieldstatusArr = [];
        let supplylinestatusArr = [];
        const battleInfosArr = [];
        const battleArr = [];
        for (const iterator of data.set) {
          switch (iterator.key) {
            case "BattleInfo":
              battleInfosArr.push(iterator.value);
              break;
            case "battle":
              battleArr.push(iterator.value);
              break;
            case "battlefieldstatus":
              battlefieldstatusArr.push(iterator.value);
              if (battlefieldstatusArr.length > 500) {
                webContents.send("updateBattlefieldstatusBatch", battlefieldstatusArr);
                battlefieldstatusArr = [];
              }
              break;
            case "supplylinestatus":
              supplylinestatusArr.push(iterator.value);
              if (supplylinestatusArr.length > 500) {
                webContents.send("updateSupplylinestatusBatch", supplylinestatusArr);
                supplylinestatusArr = [];
              }
              break;
            case "war":
              if (iterator.value.sequelwarid !== "0") {
                // TODO make popup to ask user to switch.
                console.log(`${iterator.value.id} ended, switching to: ${iterator.value.sequelwarid}`);
                client.sendPacket("join_war_request", {
                  warid: Long.fromString(iterator.value.sequelwarid),
                  factionid: Long.ZERO,
                  playedFirstBlood: 0,
                });
              }
              break;
          }
        }
        if (battlefieldstatusArr.length > 0) {
          webContents.send("updateBattlefieldstatusBatch", battlefieldstatusArr);
        }
        if (battleArr.length > 0) {
          webContents.send("updateBattlesBatch", battleArr);
        }
        if (battleInfosArr.length > 0) {
          webContents.send("setBattleInfosBatch", battleInfosArr);
        }
        if (supplylinestatusArr.length > 0) {
          webContents.send("updateSupplylinestatusBatch", supplylinestatusArr);
        }
      } else if (data?.delete) {
        const battleInfosArr = [];
        const battleArr = [];
        for (const iterator of data.delete) {
          switch (iterator.key) {
            case "BattleInfo":
              battleInfosArr.push(iterator.value);
              break;
            case "battle":
              battleArr.push(iterator.value);
              break;
            // TODO Add supplylinestatus delete key and logic!!!
          }
          console.log(`deleted: ${iterator.key} id: ${iterator.value}`);
        }
        if (battleInfosArr.length > 0) {
          webContents.send("deleteBattleInfosBatch", battleInfosArr);
        }
        if (battleArr.length > 0) {
          webContents.send("deleteBattlesBatch", battleArr);
        }
      }
    }
  }).on("LoginQueueUpdate", (pos) => {
    webContents.send("LoginQueueUpdate", pos);
  }).on("closed", () => {
    console.log("Socket closed!");
    console.log(`After ${Date.now() - startTime}ms`);
  });
}

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

